[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist/client"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[env]
  VITE_API_URL = "https://fraudia-claims-production-cd87.up.railway.app"
